# Generated by Django 3.1.5 on 2024-09-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240915_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_motified',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
