# Generated by Django 5.0.6 on 2024-09-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_date_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_odered',
            new_name='date_ordered',
        ),
    ]
